version: '2'

services:
   db:
     image: mariadb:10.3
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: database
       MYSQL_USER: user
       MYSQL_PASSWORD: password

   web:
     image: icodex/docker-nginx-php:latest
     ports:
       - 80
     volumes:
       - app:/app
     restart: always
     environment:
       MYSQL_HOST: db:3306
       MYSQL_DATABASE: database
       MYSQL_USER: user
       MYSQL_PASSWORD: password
       MEMCACHED_HOST: memcached:11211
       REDIS_HOST: redis:6379

   redis:
     image: redis:latest
     ports:
       - 6379
     volumes:
       - data:/data
     restart: always

   memcached:
     image: memcached:1.5
     ports:
       - 11211
     restart: always

   lb:
     image: icodex/docker-haproxy:latest
     ports:
       - 80
       - 443
     volumes:
       - haproxy:/usr/local/etc/haproxy
     restart: always
     environment:
       WEB_HOST: web:80


volumes:
    db_data:
    app:
    data:
    haproxy:

